typedef struct t_tdo t_tdo;
typedef struct t_tasks t_tasks;
typedef struct t_done t_done;
typedef struct t_pessoas t_pessoas;
typedef struct t_doing t_doing;
typedef struct t_data t_data;
t_pessoas *cria_lista(void);
t_tdo *cria_lista2(void);
t_doing *cria_lista3(void);
t_done *cria_lista4(void);
t_pessoas *add_pessoa(t_pessoas *,char *,char *,int);
int comparadatas(t_data *,t_data *);
t_tdo *inserir_todo(t_tdo *,char *,int ,int);
t_done *inserir_done(t_done *,char *,int ,int ,t_pessoas *, t_data)
void imprime_t_done(t_done *);
void imprimepessoas(t_pessoas *);
void imprime_todo(t_tdo *);
void imprime_tarefa_pessoas(t_doing *);
void imprime_tudo(t_pessoas *, t_doing *,t_tdo *, t_done *);
t_done *finishing(t_doing *,t_done *,int,t_pessoas *,t_data);
t_doing *move_to_do(t_tdo *,t_doing *,int ,t_pessoas *,t_data);
t_tdo *move_doing(t_doing *,t_tdo *,int);
void sort_doing(t_doing *);
void update_done(t_done *);
void update_td(t_tdo *);
void updateall(t_done *,t_doing *,t_tdo *,t_pessoas *);
t_doing *inserir_doing(t_doing *,char *,int,int,t_pessoas *,t_data );
int compara_semana(int ,int ,int ,char *,t_doing *);
void AlterarPesssoa(t_doing *,t_pessoas *,int );
int VerificarMaxTarefa(int,t_doing *,char *);
